include:
   - project: nse/ci
     file:
        - /ci/lib/tox-docker.yml
        - /ci/jobs/check-version.yml
        - /ci/jobs/check-packaging.yml
        - /ci/jobs/lint.yml
        - /ci/jobs/docs.yml
        - /ci/jobs/build-package.yml
        - /ci/jobs/publish-package.yml
        - /ci/jobs/publish-docs.yml
        - /ci/jobs/tag.yml
   - project: neuromath/ci
     file:
        - /ci/jobs/auto-release.yml
        - /ci/lib/pytest-template.yml
        - /ci/jobs/py36.yml
        - /ci/jobs/py37.yml
        - /ci/jobs/py38.yml
        - /ci/jobs/coverage.yml

.tox-template:
  # Using the same image as DVF
  image: docker-registry-default.ocp.bbp.epfl.ch/bbp-ou-cells/data-validation-framework:latest

py36:
   # Using Kubernetes runner with custom memory amount
   tags:
      - kubernetes
   variables:
      KUBERNETES_CPU_LIMIT: 4
      KUBERNETES_CPU_REQUEST: 4
      KUBERNETES_MEMORY_LIMIT: 4Gi
      KUBERNETES_MEMORY_REQUEST: 4Gi
      PYTEST_NPROCS: 4

lint:
   # Using Kubernetes runner with custom memory amount
   tags:
      - kubernetes
   variables:
      KUBERNETES_CPU_LIMIT: 1
      KUBERNETES_CPU_REQUEST: 1
      KUBERNETES_MEMORY_LIMIT: 4Gi
      KUBERNETES_MEMORY_REQUEST: 4Gi
      PYLINT_NPROCS: 1
