name: Check PR titles using commitlint

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  check-pr-title:
    name: Check PR title
    runs-on: ubuntu-latest
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g --force commitlint @commitlint/cli commitlint-plugin-cleanfeet
      - run: npm install conventional-changelog-conventionalcommits
      - run: touch .git/COMMIT_EDITMSG
      - run: echo "$PR_TITLE" | commitlint
