name: Trigger MyBinder build

on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  trigger-binder-build:
    name: Launch the build of the docker image used by MyBinder
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: BlueBrain/NeuroTS
          service-name: gh
          target-state: ${{github.ref_name}}
          debug: true
