name: Trigger MyBinder build

on:
  pull_request:  # TODO: REMOVE THIS BEFORE MERGING
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  trigger-binder-build:
    name: Launch the build of the docker image used by MyBinder
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: cache binder build on mybinder.org
        uses: jupyterhub/repo2docker-action@master
        with:
          NO_PUSH: true
          MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org with the branch that was pushed on.
